name: Deploy to Firebase

on:
  push:
    branches:
      - master

env:
  REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  REACT_APP_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
  REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  REACT_APP_ENV_TEST: ${{ secrets.FIREBASE_TOKEN.FIREBASE_ENV_TEST }}

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.FIREBASE_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          channelId: live
